version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installation des dépendances"
      - python -m venv venv
      - source venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt || true
      - pip install pytest pytest-cov

  pre_build:
    commands:
      - echo "Pré-build"
      - python --version
      - pip --version
      - mkdir -p reports

  build:
    commands:
      - echo "Lancement des tests"
      - pytest --junitxml=reports/junit-report.xml --cov=. --cov-report=xml:reports/coverage.xml

  post_build:
    commands:
      - echo "Build terminé"

reports:
  pytest-report:
    files:
      - junit-report.xml
    base-directory: reports
    file-format: JUNITXML

artifacts:
  files:
    - reports/**/*
